services:
  users-service:
    build: users-service/.
    ports:
      - "8081:8081"
    depends_on:
      - users-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  products-service:
    build: products-service/.
    ports:
      - "8082:8082"
    depends_on:
      - products-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  orders-service:
    build: orders-service/.
    ports:
      - "8083:8083"
    depends_on:
      - orders-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  users-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  products-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  orders-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres