server:
  port: 8083

users:
  server:
    url: http://users-service:8081

products:
  server:
    url: http://products-service:8082

spring:
  datasource:
    url: jdbc:postgresql://orders-db:5432/orders
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true