server:
  port: 8083

users:
  server:
    url: ${USERS_SERVER_URL}

products:
  server:
    url: ${PRODUCTS_SERVER_URL}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true